### ISSUE TITLE
why run in another ip?

### ISSUE THREAD

**Issue by johnfelipe** [Pratyush-exe/breast-cancer-detector-app#2]
192.168.0.11 - - [28/May/2022 21:57:05] "GET / HTTP/1.1" 200 -
	[2022-05-28 21:57:13,161] ERROR in app: Exception on /predict [POST]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
		response = self.full_dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
		raise value
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
		rv = self.dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "/root/breast-cancer-detector-app/app.py", line 44, in upload
		preds = model_predict(file_path, model)[0][0]
	  File "/root/breast-cancer-detector-app/app.py", line 20, in model_predict
		img = image.load_img(img_path, target_size=(100, 100))
	AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
	192.168.0.11 - - [28/May/2022 21:57:13] "POST /predict HTTP/1.1" 500 -

**Comment by Pratyush-exe** [comment]
Model was deployed in heroku, currently its disabled, hence the error
